Repository amgrubb/BloomingLeaf, pull requests merged in 2021-07, with the labels that each got.

#457 Ck issue434
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/BackboneModelsOther.js
  leaf-ui/rappid-extensions/LinkInspector.js
  leaf-ui/rappid-extensions/joint.extensions.js
Labels: backbone, bug

#460 IVT Backbone
  leaf-ui/css/analysis_style.css
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/IntermediateValues.js
Labels: backbone, needs testing, refactor

#461 Started Configurations Revamp in new branch
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/BackboneModelsAnalysis.js
  leaf-ui/rappid-extensions/ConfigInspector.js
Labels: backbone

#486 Global Variable Removable
  leaf-ui/index.html
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/initializeElements.js
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/object/analysisObjects.js
  leaf-ui/js/object/modelObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/js/onFunctionsBothWindows.js
  leaf-ui/js/onFunctionsNextState.js
  leaf-ui/rappid-extensions/ActorInspector.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/ConfigInspector.js
  leaf-ui/rappid-extensions/ElementInspector.js
  leaf-ui/rappid-extensions/IntermediateValues.js
Labels: cleanup, needs testing

#491 CSS issues with Assignments Table and IVT
  leaf-ui/css/analysis_html.css
  leaf-ui/css/analysis_style.css
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/IntermediateValues.js
Labels: backbone

#490 Fixed #456
  leaf-ui/js/onFunctions.js
Labels: bug

#494 Result (Configuration) Deletion Fix
  leaf-ui/rappid-extensions/ConfigInspector.js
Labels: backbone, frontend

#498 Fixed issue #492
  leaf-ui/rappid-extensions/BackboneModelsOther.js
Labels: backbone

#496 Yif inspector view redesign
  leaf-ui/css/style.css
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: backbone, frontend

#487 Fixing the visual issues for the toolbar and sidebar
  leaf-ui/analysis.html
  leaf-ui/css/analysis_style.css
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ActorInspector.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/ConfigInspector.js
  leaf-ui/rappid-extensions/ElementInspector.js
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug

#497 Renamed absTime in LinkBB to absTP
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/BackboneModelsOther.js
Labels: backbone

#503 Fixing three bugs in ElementInspector.js
  leaf-ui/css/style.css
  leaf-ui/rappid-extensions/ElementInspector.js
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: backbone, bug

#513 Fixes two bugs in ElementInspector.js and two bugs in LinkInspector.js
  leaf-ui/css/style.css
  leaf-ui/rappid-extensions/ElementInspector.js
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: backbone, bug

#519 getInitialSatValue() + the model being undefined in onFunctions.js fix
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: backbone, frontend
