Repository amgrubb/BloomingLeaf, pull requests merged in 2021-02, with the labels that each got.

#270 Save and load functionality for analysis configurations and results
  leaf-ui/index.html
  leaf-ui/js/Readme.md
  leaf-ui/js/backendComm.js
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/object/Class.js
  leaf-ui/js/objects.js
  leaf-ui/js/onFunctions.js
Labels: model-management

#276 Issue 272
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/objects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
Labels: bug, model-management

#284 Adjust UI for results/configs
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/object/Class.js
  leaf-ui/js/onFunctions.js
Labels: bug, frontend, model-management, ux-bug

#283 Naming feature
  leaf-ui/css/analysis_style.css
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/objects.js
Labels: enhancement, feature, frontend, model-management
