Repository amgrubb/BloomingLeaf, pull requests merged in 2021-08, with the labels that each got.

#524 Constraint Assignments
  leaf-ui/rappid-extensions/AssignmentsTable.js
Labels: backbone, bug

#526 Fixed EVO Coloring Bug for State
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ConfigInspector.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug

#532 EVO-related issues with satvalue and slider
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ConfigInspector.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug, evo

#531 Fixing absTime bugs
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug, backbone

#534 Reimplemented the new backbone structure in #btn-clear-elabel
  leaf-ui/js/onFunctions.js
Labels: bug, backbone

#545 Re-implement cycle detection and syntax checking with new backbone objects (#517)
  leaf-ui/js/backendComm.js
  leaf-ui/js/errorDetection.js
  leaf-ui/js/onFunctions.js
Labels: frontend, backbone

#543 Fixed issues below
  leaf-ui/css/analysis_html.css
  leaf-ui/css/style.css
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug

#555 Re-implementing Next State in Backbone
  leaf-analysis/bin/Blooming.jar
  leaf-analysis/src/gson_classes/IAnalysisRequest.java
  leaf-analysis/src/gson_classes/IOSolution.java
  leaf-analysis/src/simulation/BICSPAlgorithm.java
  leaf-analysis/src/simulation/BICSPPath.java
  leaf-analysis/src/simulation/BICSPState.java
  leaf-analysis/src/simulation/CSPIntentions.java
  leaf-analysis/src/simulation/CSPPath.java
  leaf-analysis/src/simulation/CSPSolve.java
  leaf-analysis/src/simulation/Main.java
  leaf-analysis/src/simulation/ModelSpec.java
  leaf-ui/analysis.html
  leaf-ui/css/analysis_html.css
  leaf-ui/css/analysis_style.css
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/js/analysis.js
  leaf-ui/js/backendComm.js
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/initializeElements.js
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/next-state.js
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/js/onFunctionsBothWindows.js
  leaf-ui/js/onFunctionsNextState.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/BackboneModelsAnalysis.js
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/ElementInspector.js
  leaf-ui/rappid-extensions/joint.extensions-next.js
Labels: backbone, next-state

#556 Fixed absTime and element inspector bugs
  leaf-ui/analysis.html
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug, backbone
