Repository amgrubb/BloomingLeaf, pull requests merged in 2021-06, with the labels that each got.

#371 Update readme root
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  NODE-README.md
  README.md
  leaf-analysis/.classpath
  leaf-analysis/src/interface_objects/AnalysisResult.java
  leaf-analysis/src/interface_objects/FuncWrapper.java
  leaf-analysis/src/interface_objects/InputAnalysis.java
  leaf-analysis/src/interface_objects/InputLink.java
  leaf-analysis/src/interface_objects/OutputModel.java
  leaf-analysis/src/simulation/TroposCSPAlgorithm.java
  leaf-analysis/stored-models/default.json
  leaf-analysis/stored-models/simple-AND
  leaf-analysis/stored-models/single-node
  leaf-analysis/stored-models/testEB-Values
  testForIssue87.json
  testResult.txt
Labels: cleanup

#369 Class migration
  leaf-ui/analysis.html
  leaf-ui/index.html
  leaf-ui/js/initializeElements.js
  leaf-ui/js/object/analysisObjects.js
  leaf-ui/js/object/evoObjects.js
  leaf-ui/js/object/modelObjects.js
  leaf-ui/js/object/viewObjects.js
  leaf-ui/js/objects.js
  leaf-ui/testRunner.html
Labels: backbone

#367 Dead code cleanup
  leaf-ui/js/initializeElements.js
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/onFunctions.js
Labels: cleanup, frontend, needs testing, refactor

#378 Remove NB tag after switching link type
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: ramp-up

#381 issue #375 And/Or end selections fixed
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug, ramp-up

#383 Fixed: issue #374 in LinkInspector
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug, ramp-up

#387 Add params to joint.js elements/links/graph to prep for refactor
  leaf-ui/js/analysis.js
  leaf-ui/js/initializeElements.js
  leaf-ui/js/object/modelObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/joint.extensions.js
Labels: backbone, frontend, refactor

#388 Issue #372 ElementInspector.js no-value dropdown fix and Issue #377 modelObjects.js UD function drop down fix
  leaf-ui/js/object/modelObjects.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug, ramp-up

#379 Fixed issue #375 LinkInspector dropdown in evolving relationship
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug, ramp-up

#384 Issue376 Fixed in LinkInspector
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug

#397 Analysis inspector backbone
  leaf-ui/css/analysis_style.css
  leaf-ui/index.html
  leaf-ui/js/initializeElements.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
  leaf-ui/rappid-extensions/ConfigInspector.js
  leaf-ui/rappid-extensions/IntermediateValues.js
Labels: backbone, refactor

#398 ActorInspector is now backbone structure
  leaf-ui/js/initializeElements.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ActorInspector.js
  leaf-ui/rappid-extensions/joint.extensions.js
Labels: backbone, refactor

#400 Fixed issue #389
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug, ramp-up

#432 Combining LinkBBM with LinkInspector
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/object/modelObjects.js
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/BackboneModelsOther.js
  leaf-ui/rappid-extensions/LinkInspector.js
  leaf-ui/rappid-extensions/joint.extensions.js
Labels: backbone

#436 Basic Assignments Table structure implementation
  leaf-ui/css/analysis_style.css
  leaf-ui/index.html
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/AnalysisModels.js
  leaf-ui/rappid-extensions/AssignmentsTable.js
  leaf-ui/rappid-extensions/BackboneModelsIntention.js
  leaf-ui/rappid-extensions/BackboneModelsOther.js
  leaf-ui/rappid-extensions/joint.extensions.js
Labels: backbone, refactor

#455 Fixed Issue #445
  leaf-ui/rappid-extensions/LinkInspector.js
Labels: bug
