Repository amgrubb/BloomingLeaf, pull requests merged in 2021-04, with the labels that each got.

#316 Fix Documentation link to download
  leaf-ui/index.html
Labels: bug, frontend, model-management

#323 Reset graph UI when clearing results/configs
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/onFunctions.js
Labels: bug, model-management, ux-bug

#322 Scroll bar
  leaf-ui/index.html
  leaf-ui/js/initializeElements.js
Labels: low priority, ui/aesthetic, ux-bug

#330 added spinner under cursor for explore next states
  leaf-ui/css/analysis_html.css
  leaf-ui/css/style.css
  leaf-ui/js/analysis.js
  leaf-ui/js/backendComm.js
  leaf-ui/rappid-extensions/AnalysisInspector.js
Labels: feature, frontend, model-management

#324 Correctly update mode tag in modeling view
  leaf-ui/js/onFunctions.js
Labels: bug, ux-bug

#325 Fixes 3 outstanding issues from develop branch - #255, #304, #314
  leaf-ui/css/style.css
  leaf-ui/index.html
  leaf-ui/js/onFunctions.js
  leaf-ui/rappid-extensions/ElementInspector.js
Labels: bug, low priority, ux-bug

#343 Resolves bugs with interaction of actors and intentions
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/object/Class.js
  leaf-ui/js/onFunctions.js
Labels: bug, exemplar, frontend
