Repository amgrubb/BloomingLeaf, pull requests merged in 2021-03, with the labels that each got.

#301 Fix load-clear-reload bug
  leaf-ui/js/loadSaveFunctions.js
Labels: bug, frontend, low priority, model-management

#306 Clear results functionality
  leaf-ui/index.html
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/objects.js
  leaf-ui/js/onFunctions.js
Labels: feature, frontend, model-management

#309 Add alert during rename when name is taken
  leaf-ui/js/displayAnalysis.js
Labels: feature, low priority, model-management

#308 Slider starts at 0 when switching results
  leaf-ui/js/backendComm.js
  leaf-ui/js/displayAnalysis.js
Labels: bug, frontend, low priority, model-management

#310 Iss294 Model Editing Features
  leaf-ui/js/displayAnalysis.js
  leaf-ui/js/initializeElements.js
  leaf-ui/js/loadSaveFunctions.js
  leaf-ui/js/objects.js
  leaf-ui/js/onFunctions.js
Labels: feature, frontend, model-management
